site_name: DCNN Accelerator
nav:
    - Home: index.md
    - About: about.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
extra_css: [extra.css]
