site_name: DCNN Accelerator
nav:
    - Home: index.md
    - Software: software.md
    - Hardware: hardware.md
    - Verification: verification.md
    - Build Your Own: build_your_own.md
    - About: about.md

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
extra_css: [extra.css]
